### ISSUE TITLE
Admin Page Content : Save button make crash

### ISSUE THREAD

**Issue by R-Men** [rohsyl/omega-l#12]
I added a "Gallery" component to an empty page, clicked on "save" and the page crashed. 

<details><summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/5238616/48842688-2b781480-ed95-11e8-8dc4-eb71df8c938a.png)

![image](https://user-images.githubusercontent.com/5238616/48842751-5b271c80-ed95-11e8-8261-082f3b163bf3.png)

</details>

**Comment by rohsyl** [comment]
fixed in commit [13cd2be](https://github.com/rohsyl/omega-l/commit/13cd2be48721d7b93402e0593a70d27eb03131fa)
