### ISSUE TITLE
Media : php-gd required

### ISSUE THREAD

**Issue by R-Men** [rohsyl/omega-l#15]
The php library php-gd is required for images to be shown in admin and displayed in public but not installed by Omega-L.

for yet we have to install it manually with
`sudo apt install php7.2-gd`

**Comment by rohsyl** [comment]
For the requirements, you should check out the requirement of [Laravel 5.7](https://laravel.com/docs/5.7/installation)

Here the [installation guide](https://rohsyl.github.io/omega-l-documentation/install.html)
