### ISSUE TITLE
Admin Plugin Divided Content : Divided content page not showing

### ISSUE THREAD

**Issue by R-Men** [rohsyl/omega-l#17]
The Divided content module doesn't specify that the page to use should be a child of the page itself. 

There is no pages shown if they are not set as child 

![image](https://user-images.githubusercontent.com/5238616/48847709-7ba9a380-eda2-11e8-94ae-60cbb90ad66e.png)

and without any page set in the divided content there is an error in public part : 

![image](https://user-images.githubusercontent.com/5238616/48847882-e824a280-eda2-11e8-8130-1318703b0138.png)

**Comment by rohsyl** [comment]
You must reinstall the plugin to see the changes...
