### ISSUE TITLE
Admin Page Content : Error on saving

### ISSUE THREAD

**Issue by R-Men** [rohsyl/omega-l#20]
I created a page (this page is a child from an other)

I added 3 components (image, text, text) and when I save it crashes 

![image](https://user-images.githubusercontent.com/5238616/48849564-e957ce80-eda6-11e8-8742-b8093cf3cf18.png)

**Comment by R-Men** [comment]
Maybe that can help you : 
```
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'value' cannot be null (SQL: insert into `form_entry_values` (`value`, `fkFormEntry`, `fkModule`, `updated_at`, `created_at`) values (, 13, 14, 2018-11-21 15:05:46, 2018-11-21 15:05:46))
```

**Comment by rohsyl** [comment]
I have changed a field in the database so you have two choice :
1. Re-install your instance of the CMS
2. Change the field "value" in the table "form_entry_values" and remove the "not null" flag.
