### ISSUE TITLE
Admin Menu Editor : adding a "Open in new page" option

### ISSUE THREAD

**Issue by R-Men** [rohsyl/omega-l#22]
It would be nice to have an option to open external links in menus as a new page 
`target="_blank"` attribute

![image](https://user-images.githubusercontent.com/5238616/48978039-f2e27e80-f0a5-11e8-8ef8-f37b51998572.png)
 just a check box "open in new tab" would be enough

**Comment by rohsyl** [comment]
Now you can choose to open in the link in a new tab by clicking on the gear icon

![image](https://user-images.githubusercontent.com/18440665/49140039-8a88dc80-f2f3-11e8-98b7-e94e1ec648b0.png)

It will open a modal in which you can edit this options.

![image](https://user-images.githubusercontent.com/18440665/49140132-c15ef280-f2f3-11e8-9a05-ce7831c09e63.png)

**Comment by rohsyl** [comment]
You also have to change your htmlstruct of your menu in theme.
there is a new parameter for each li_* item.

![image](https://user-images.githubusercontent.com/18440665/49140234-0daa3280-f2f4-11e8-830f-512756e6795e.png)

- for `li_nochildren` it's %4$s
- for `li_nochildrenactiv` it's %4$s
- for `li_children` it's %5$s
- for `li_childrenactiv` it's %5$s

This will add `target="_blank"` of the Open in a new tab option is enabled
