### ISSUE TITLE
Admin Plugin Contact : Logo not resized

### ISSUE THREAD

**Issue by R-Men** [rohsyl/omega-l#23]
The logo from contact module is not resized 

![image](https://user-images.githubusercontent.com/5238616/48978384-21af2380-f0ab-11e8-802d-d7e844325773.png)

in the public part qe see that the logo is way too big  

![image](https://user-images.githubusercontent.com/5238616/48978379-122fda80-f0ab-11e8-8a7c-fdf724c2d05c.png)

**Comment by rohsyl** [comment]
Basically, the idea was to upload a logo with the right size or to resize it with css. Not to resize it automatically
