### ISSUE TITLE
Admin Plugin GoogleMaps : Doesn't appear in components

### ISSUE THREAD

**Issue by R-Men** [rohsyl/omega-l#26]
Plugin is installed : 

![image](https://user-images.githubusercontent.com/5238616/48979043-72c41500-f0b5-11e8-9e4a-f1179a47b8e1.png)

Doesn't show in components in a page : 

![image](https://user-images.githubusercontent.com/5238616/48979054-88d1d580-f0b5-11e8-860a-526bd18e86ab.png)

**Comment by rohsyl** [comment]
You need to reinstall the plugin
