### ISSUE TITLE
Admin Page Creation : recreation of an old page

### ISSUE THREAD

**Issue by R-Men** [rohsyl/omega-l#29]
Can't create a page with the name of a previously deleted one

it gives out a error
 
![image](https://user-images.githubusercontent.com/5238616/48980303-7a8cb500-f0c7-11e8-898d-171b739da78b.png)

Maybe add or `_deleted` to deleted pages so it won't interfer with new pages creation

**Comment by rohsyl** [comment]
Page will have their slug changed when soft-deleting
