### ISSUE TITLE
Migration : Media error (failed to open stream: No such file or directory)

### ISSUE THREAD

**Issue by R-Men** [rohsyl/omega-l#34]
When migrating on a new server, check if you take the media folder with, otherwise it will come to this error : 
 failed to open stream: No such file or directory

![image](https://user-images.githubusercontent.com/5238616/49176594-6b1d9e00-f34b-11e8-965c-e8da1c17a171.png)

the folder is located at : `public/media`
this folder is ignored by .gitignore

**Comment by rohsyl** [comment]
Doc updated. In the install.md file, section [migration](https://github.com/rohsyl/omega-l-documentation/blob/master/install.md#migration)
