### ISSUE TITLE
Installation : Provide good instructions when defining the password

### ISSUE THREAD

**Issue by stevenroh** [rohsyl/omega-l#37]
The password is validated with a regex : https://github.com/rohsyl/omega-l/blob/56a0661a52c1d4923c5ae63004aa3298868b6c84/app/Http/Requests/Install/SiteAndUserRequest.php#L31

Howewer, error message is unclear and should give password requirements.

![Error about the password format](https://user-images.githubusercontent.com/1651603/49331548-f17dee00-f59e-11e8-81ed-8f695822a662.png)

PS : `LzzGaXcxDMpUXMa8MSGxX82cdwHQp3` looks a good password but cannot be used

**Comment by rohsyl** [comment]
I will remove the regex and let the user use the password he want with no restrictions.
