### ISSUE TITLE
File upload is not avaible

### ISSUE THREAD

**Issue by FarkinatioN** [rohsyl/omega-l#65]
**Describe the bug**
When I wanted to upload medias on the CMS, a pop-up says that the media folder is not writable. After I checked if the folder exists, I saw that he doesn't exist.

**To Reproduce**
1. Go to 'Mediatheque'
2. Click on 'upload files'
3. See error

**Expected behavior**
Create folder

**Screenshots**
![Capture d’écran de 2019-05-01 11-00-24](https://user-images.githubusercontent.com/32563222/57011500-42534a80-6c02-11e9-8823-e2297e44f1c8.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: chrome
 - Version: 73.0.3683.103

**Comment by rohsyl** [comment]
Duplicated of #63.

It will  be fixed soon.

Quick fix:
create the folder manually.
